# Generated by Django 4.0 on 2022-04-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
